name: Preview Deployment - Website
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WWW }}
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  TURBO_TEAM: ${{ secrets.VERCEL_ORG_ID }}
  TIPTAP_PRO_TOKEN: ${{ secrets.TIPTAP_PRO_TOKEN }}
  SOLOMON_AI_TOKEN: ${{ secrets.SOLOMON_AI_TOKEN }}

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      # - name: 🔦 Run linter
      #   run: bun run lint --filter=@midday/dashboard
      # - name: 🪐 Check TypeScript
      # #   run: bun run typecheck --filter=@midday/dashboard
      # - name: 🧪 Run unit tests
      #   run: bun run test
      - name: 📤 Pull Vercel Environment Information
        run: bunx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: 🏗 Build Project Artifacts
        run: bunx vercel build --token=${{ secrets.VERCEL_TOKEN }}
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - name: Deploy Project Artifacts to Vercel
        run: bunx vercel deploy --prebuilt --archive=tgz --token=${{ secrets.VERCEL_TOKEN }}
